// Code generated by mockery v2.53.3. DO NOT EDIT.

package main

import mock "github.com/stretchr/testify/mock"

// mockCronjobInterface is an autogenerated mock type for the cronjobInterface type
type mockCronjobInterface struct {
	mock.Mock
}

type mockCronjobInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCronjobInterface) EXPECT() *mockCronjobInterface_Expecter {
	return &mockCronjobInterface_Expecter{mock: &_m.Mock}
}

// newMockCronjobInterface creates a new instance of mockCronjobInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCronjobInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCronjobInterface {
	mock := &mockCronjobInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
