---
# Source: loki/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-minio
  namespace: "monitoring"
  labels:
    app: minio
    chart: minio-4.0.12
    release: loki
    heritage: Helm
type: Opaque
data:
  rootUser: "ZW50ZXJwcmlzZS1sb2dz"
  rootPassword: "c3VwZXJzZWNyZXQ="
