---
# Source: grafana/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana
  namespace: monitoring
  labels:
    helm.sh/chart: grafana-6.48.0
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
    app.kubernetes.io/version: "9.3.1"
    app.kubernetes.io/managed-by: Helm
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    [grafana_net]
    url = https://grafana.net
    [log]
    mode = console
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    [server]
    domain = ''
    [auth]
    signout_redirect_url = https://192.168.56.2/cas/logout
    [auth.basic]
    enabled = false
    [auth.generic_oauth]
    name = OAuth
    icon = signin
    enabled = true
    client_id = cas-sa
    client_secret = cas-sa-pw
    empty_scopes = false
    auth_url = https://192.168.56.2/cas/oauth2.0/authorize
    token_url = https://192.168.56.2/cas/oauth2.0/token
    api_url = https://192.168.56.2/cas/oauth2.0/profile
    allowed_domains = mycompany.com mycompany.org 192.168.56.2
    allow_sign_up = true
    tls_skip_verify_insecure = true
    use_pkce = true
