---
# Source: loki/templates/gateway/secret-gateway.yaml
apiVersion: v1
kind: Secret
metadata:
  name: loki-gateway
  labels:
    helm.sh/chart: loki-3.8.0
    app.kubernetes.io/name: loki
    app.kubernetes.io/instance: loki
    app.kubernetes.io/version: "2.7.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
stringData:
  .htpasswd: |
    loki:$2a$10$z2pZRvwY4dnDibvXvzfON.V10mj5XXMNAzxl6fEan0xhnwIMjnv2K
