// Code generated by mockery v2.20.0. DO NOT EDIT.

package debug

import mock "github.com/stretchr/testify/mock"

// mockDoguLogLevelRegistry is an autogenerated mock type for the doguLogLevelRegistry type
type mockDoguLogLevelRegistry struct {
	mock.Mock
}

type mockDoguLogLevelRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguLogLevelRegistry) EXPECT() *mockDoguLogLevelRegistry_Expecter {
	return &mockDoguLogLevelRegistry_Expecter{mock: &_m.Mock}
}

// MarshalFromCesRegistryToString provides a mock function with given fields:
func (_m *mockDoguLogLevelRegistry) MarshalFromCesRegistryToString() (string, error) {
	ret := _m.Called()

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func() (string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarshalFromCesRegistryToString'
type mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call struct {
	*mock.Call
}

// MarshalFromCesRegistryToString is a helper method to define mock.On call
func (_e *mockDoguLogLevelRegistry_Expecter) MarshalFromCesRegistryToString() *mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call {
	return &mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call{Call: _e.mock.On("MarshalFromCesRegistryToString")}
}

func (_c *mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call) Run(run func()) *mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call) Return(_a0 string, _a1 error) *mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call) RunAndReturn(run func() (string, error)) *mockDoguLogLevelRegistry_MarshalFromCesRegistryToString_Call {
	_c.Call.Return(run)
	return _c
}

// UnMarshalFromStringToCesRegistry provides a mock function with given fields: unmarshal
func (_m *mockDoguLogLevelRegistry) UnMarshalFromStringToCesRegistry(unmarshal string) error {
	ret := _m.Called(unmarshal)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(unmarshal)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnMarshalFromStringToCesRegistry'
type mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call struct {
	*mock.Call
}

// UnMarshalFromStringToCesRegistry is a helper method to define mock.On call
//   - unmarshal string
func (_e *mockDoguLogLevelRegistry_Expecter) UnMarshalFromStringToCesRegistry(unmarshal interface{}) *mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call {
	return &mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call{Call: _e.mock.On("UnMarshalFromStringToCesRegistry", unmarshal)}
}

func (_c *mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call) Run(run func(unmarshal string)) *mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call) Return(_a0 error) *mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call) RunAndReturn(run func(string) error) *mockDoguLogLevelRegistry_UnMarshalFromStringToCesRegistry_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockDoguLogLevelRegistry interface {
	mock.TestingT
	Cleanup(func())
}

// newMockDoguLogLevelRegistry creates a new instance of mockDoguLogLevelRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockDoguLogLevelRegistry(t mockConstructorTestingTnewMockDoguLogLevelRegistry) *mockDoguLogLevelRegistry {
	mock := &mockDoguLogLevelRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
