// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import (
	"github.com/cloudogu/cesapp-lib/keys"
	mock "github.com/stretchr/testify/mock"
)

// KeyProvider is an autogenerated mock type for the keyProvider type
type KeyProvider struct {
	mock.Mock
}

// FromPrivateKeyPath provides a mock function with given fields: path
func (_m *KeyProvider) FromPrivateKeyPath(path string) (*keys.KeyPair, error) {
	ret := _m.Called(path)

	var r0 *keys.KeyPair
	if rf, ok := ret.Get(0).(func(string) *keys.KeyPair); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.KeyPair)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
