// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	apiv1 "github.com/cloudogu/k8s-component-lib/api/v1"

	mock "github.com/stretchr/testify/mock"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockComponentClient is an autogenerated mock type for the componentClient type
type mockComponentClient struct {
	mock.Mock
}

type mockComponentClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockComponentClient) EXPECT() *mockComponentClient_Expecter {
	return &mockComponentClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockComponentClient) Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1.Component, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *apiv1.Component
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*apiv1.Component, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *apiv1.Component); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apiv1.Component)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockComponentClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockComponentClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *mockComponentClient_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockComponentClient_Get_Call {
	return &mockComponentClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockComponentClient_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *mockComponentClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *mockComponentClient_Get_Call) Return(_a0 *apiv1.Component, _a1 error) *mockComponentClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockComponentClient_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*apiv1.Component, error)) *mockComponentClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// newMockComponentClient creates a new instance of mockComponentClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockComponentClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockComponentClient {
	mock := &mockComponentClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
