// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"
)

// mockBackupScheduleClient is an autogenerated mock type for the backupScheduleClient type
type mockBackupScheduleClient struct {
	mock.Mock
}

type mockBackupScheduleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBackupScheduleClient) EXPECT() *mockBackupScheduleClient_Expecter {
	return &mockBackupScheduleClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, backupSchedule, opts
func (_m *mockBackupScheduleClient) Create(ctx context.Context, backupSchedule *v1.BackupSchedule, opts metav1.CreateOptions) (*v1.BackupSchedule, error) {
	ret := _m.Called(ctx, backupSchedule, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.BackupSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) (*v1.BackupSchedule, error)); ok {
		return rf(ctx, backupSchedule, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) *v1.BackupSchedule); ok {
		r0 = rf(ctx, backupSchedule, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BackupSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, backupSchedule, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupScheduleClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockBackupScheduleClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - backupSchedule *v1.BackupSchedule
//   - opts metav1.CreateOptions
func (_e *mockBackupScheduleClient_Expecter) Create(ctx interface{}, backupSchedule interface{}, opts interface{}) *mockBackupScheduleClient_Create_Call {
	return &mockBackupScheduleClient_Create_Call{Call: _e.mock.On("Create", ctx, backupSchedule, opts)}
}

func (_c *mockBackupScheduleClient_Create_Call) Run(run func(ctx context.Context, backupSchedule *v1.BackupSchedule, opts metav1.CreateOptions)) *mockBackupScheduleClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockBackupScheduleClient_Create_Call) Return(_a0 *v1.BackupSchedule, _a1 error) *mockBackupScheduleClient_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupScheduleClient_Create_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule, metav1.CreateOptions) (*v1.BackupSchedule, error)) *mockBackupScheduleClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockBackupScheduleClient) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.BackupSchedule, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.BackupSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.BackupSchedule, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.BackupSchedule); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BackupSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupScheduleClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockBackupScheduleClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockBackupScheduleClient_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockBackupScheduleClient_Get_Call {
	return &mockBackupScheduleClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockBackupScheduleClient_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockBackupScheduleClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockBackupScheduleClient_Get_Call) Return(_a0 *v1.BackupSchedule, _a1 error) *mockBackupScheduleClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupScheduleClient_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.BackupSchedule, error)) *mockBackupScheduleClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, backupSchedule, opts
func (_m *mockBackupScheduleClient) Update(ctx context.Context, backupSchedule *v1.BackupSchedule, opts metav1.UpdateOptions) (*v1.BackupSchedule, error) {
	ret := _m.Called(ctx, backupSchedule, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.BackupSchedule
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule, metav1.UpdateOptions) (*v1.BackupSchedule, error)); ok {
		return rf(ctx, backupSchedule, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.BackupSchedule, metav1.UpdateOptions) *v1.BackupSchedule); ok {
		r0 = rf(ctx, backupSchedule, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BackupSchedule)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.BackupSchedule, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, backupSchedule, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupScheduleClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockBackupScheduleClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - backupSchedule *v1.BackupSchedule
//   - opts metav1.UpdateOptions
func (_e *mockBackupScheduleClient_Expecter) Update(ctx interface{}, backupSchedule interface{}, opts interface{}) *mockBackupScheduleClient_Update_Call {
	return &mockBackupScheduleClient_Update_Call{Call: _e.mock.On("Update", ctx, backupSchedule, opts)}
}

func (_c *mockBackupScheduleClient_Update_Call) Run(run func(ctx context.Context, backupSchedule *v1.BackupSchedule, opts metav1.UpdateOptions)) *mockBackupScheduleClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.BackupSchedule), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockBackupScheduleClient_Update_Call) Return(_a0 *v1.BackupSchedule, _a1 error) *mockBackupScheduleClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupScheduleClient_Update_Call) RunAndReturn(run func(context.Context, *v1.BackupSchedule, metav1.UpdateOptions) (*v1.BackupSchedule, error)) *mockBackupScheduleClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBackupScheduleClient creates a new instance of mockBackupScheduleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBackupScheduleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBackupScheduleClient {
	mock := &mockBackupScheduleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
