// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	batchv1 "k8s.io/api/batch/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockCronJobClient is an autogenerated mock type for the cronJobClient type
type mockCronJobClient struct {
	mock.Mock
}

type mockCronJobClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockCronJobClient) EXPECT() *mockCronJobClient_Expecter {
	return &mockCronJobClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockCronJobClient) Get(ctx context.Context, name string, opts v1.GetOptions) (*batchv1.CronJob, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *batchv1.CronJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*batchv1.CronJob, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *batchv1.CronJob); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*batchv1.CronJob)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockCronJobClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockCronJobClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *mockCronJobClient_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockCronJobClient_Get_Call {
	return &mockCronJobClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockCronJobClient_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *mockCronJobClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *mockCronJobClient_Get_Call) Return(_a0 *batchv1.CronJob, _a1 error) *mockCronJobClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockCronJobClient_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*batchv1.CronJob, error)) *mockCronJobClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// newMockCronJobClient creates a new instance of mockCronJobClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockCronJobClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockCronJobClient {
	mock := &mockCronJobClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
