// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	corev1 "k8s.io/api/core/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// mockConfigmapClient is an autogenerated mock type for the configmapClient type
type mockConfigmapClient struct {
	mock.Mock
}

type mockConfigmapClient_Expecter struct {
	mock *mock.Mock
}

func (_m *mockConfigmapClient) EXPECT() *mockConfigmapClient_Expecter {
	return &mockConfigmapClient_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockConfigmapClient) Get(ctx context.Context, name string, opts v1.GetOptions) (*corev1.ConfigMap, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *corev1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) (*corev1.ConfigMap, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, v1.GetOptions) *corev1.ConfigMap); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, v1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigmapClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockConfigmapClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts v1.GetOptions
func (_e *mockConfigmapClient_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockConfigmapClient_Get_Call {
	return &mockConfigmapClient_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockConfigmapClient_Get_Call) Run(run func(ctx context.Context, name string, opts v1.GetOptions)) *mockConfigmapClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(v1.GetOptions))
	})
	return _c
}

func (_c *mockConfigmapClient_Get_Call) Return(_a0 *corev1.ConfigMap, _a1 error) *mockConfigmapClient_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigmapClient_Get_Call) RunAndReturn(run func(context.Context, string, v1.GetOptions) (*corev1.ConfigMap, error)) *mockConfigmapClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, config, opts
func (_m *mockConfigmapClient) Update(ctx context.Context, config *corev1.ConfigMap, opts v1.UpdateOptions) (*corev1.ConfigMap, error) {
	ret := _m.Called(ctx, config, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *corev1.ConfigMap
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.ConfigMap, v1.UpdateOptions) (*corev1.ConfigMap, error)); ok {
		return rf(ctx, config, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *corev1.ConfigMap, v1.UpdateOptions) *corev1.ConfigMap); ok {
		r0 = rf(ctx, config, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*corev1.ConfigMap)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *corev1.ConfigMap, v1.UpdateOptions) error); ok {
		r1 = rf(ctx, config, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockConfigmapClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockConfigmapClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - config *corev1.ConfigMap
//   - opts v1.UpdateOptions
func (_e *mockConfigmapClient_Expecter) Update(ctx interface{}, config interface{}, opts interface{}) *mockConfigmapClient_Update_Call {
	return &mockConfigmapClient_Update_Call{Call: _e.mock.On("Update", ctx, config, opts)}
}

func (_c *mockConfigmapClient_Update_Call) Run(run func(ctx context.Context, config *corev1.ConfigMap, opts v1.UpdateOptions)) *mockConfigmapClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*corev1.ConfigMap), args[2].(v1.UpdateOptions))
	})
	return _c
}

func (_c *mockConfigmapClient_Update_Call) Return(_a0 *corev1.ConfigMap, _a1 error) *mockConfigmapClient_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockConfigmapClient_Update_Call) RunAndReturn(run func(context.Context, *corev1.ConfigMap, v1.UpdateOptions) (*corev1.ConfigMap, error)) *mockConfigmapClient_Update_Call {
	_c.Call.Return(run)
	return _c
}

// newMockConfigmapClient creates a new instance of mockConfigmapClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockConfigmapClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockConfigmapClient {
	mock := &mockConfigmapClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
