// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockBackupInterface is an autogenerated mock type for the backupInterface type
type mockBackupInterface struct {
	mock.Mock
}

type mockBackupInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBackupInterface) EXPECT() *mockBackupInterface_Expecter {
	return &mockBackupInterface_Expecter{mock: &_m.Mock}
}

// AddFinalizer provides a mock function with given fields: ctx, _a1, finalizer
func (_m *mockBackupInterface) AddFinalizer(ctx context.Context, _a1 *v1.Backup, finalizer string) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for AddFinalizer")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string) (*v1.Backup, error)); ok {
		return rf(ctx, _a1, finalizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string) *v1.Backup); ok {
		r0 = rf(ctx, _a1, finalizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, string) error); ok {
		r1 = rf(ctx, _a1, finalizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_AddFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFinalizer'
type mockBackupInterface_AddFinalizer_Call struct {
	*mock.Call
}

// AddFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
//   - finalizer string
func (_e *mockBackupInterface_Expecter) AddFinalizer(ctx interface{}, _a1 interface{}, finalizer interface{}) *mockBackupInterface_AddFinalizer_Call {
	return &mockBackupInterface_AddFinalizer_Call{Call: _e.mock.On("AddFinalizer", ctx, _a1, finalizer)}
}

func (_c *mockBackupInterface_AddFinalizer_Call) Run(run func(ctx context.Context, _a1 *v1.Backup, finalizer string)) *mockBackupInterface_AddFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string))
	})
	return _c
}

func (_c *mockBackupInterface_AddFinalizer_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_AddFinalizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_AddFinalizer_Call) RunAndReturn(run func(context.Context, *v1.Backup, string) (*v1.Backup, error)) *mockBackupInterface_AddFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// AddLabels provides a mock function with given fields: ctx, _a1
func (_m *mockBackupInterface) AddLabels(ctx context.Context, _a1 *v1.Backup) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddLabels")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_AddLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLabels'
type mockBackupInterface_AddLabels_Call struct {
	*mock.Call
}

// AddLabels is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
func (_e *mockBackupInterface_Expecter) AddLabels(ctx interface{}, _a1 interface{}) *mockBackupInterface_AddLabels_Call {
	return &mockBackupInterface_AddLabels_Call{Call: _e.mock.On("AddLabels", ctx, _a1)}
}

func (_c *mockBackupInterface_AddLabels_Call) Run(run func(ctx context.Context, _a1 *v1.Backup)) *mockBackupInterface_AddLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockBackupInterface_AddLabels_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_AddLabels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_AddLabels_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, error)) *mockBackupInterface_AddLabels_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, _a1, opts
func (_m *mockBackupInterface) Create(ctx context.Context, _a1 *v1.Backup, opts metav1.CreateOptions) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, metav1.CreateOptions) (*v1.Backup, error)); ok {
		return rf(ctx, _a1, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, metav1.CreateOptions) *v1.Backup); ok {
		r0 = rf(ctx, _a1, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, _a1, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockBackupInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
//   - opts metav1.CreateOptions
func (_e *mockBackupInterface_Expecter) Create(ctx interface{}, _a1 interface{}, opts interface{}) *mockBackupInterface_Create_Call {
	return &mockBackupInterface_Create_Call{Call: _e.mock.On("Create", ctx, _a1, opts)}
}

func (_c *mockBackupInterface_Create_Call) Run(run func(ctx context.Context, _a1 *v1.Backup, opts metav1.CreateOptions)) *mockBackupInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockBackupInterface_Create_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_Create_Call) RunAndReturn(run func(context.Context, *v1.Backup, metav1.CreateOptions) (*v1.Backup, error)) *mockBackupInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockBackupInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackupInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockBackupInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockBackupInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockBackupInterface_Delete_Call {
	return &mockBackupInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockBackupInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockBackupInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockBackupInterface_Delete_Call) Return(_a0 error) *mockBackupInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackupInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockBackupInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *mockBackupInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockBackupInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type mockBackupInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *mockBackupInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *mockBackupInterface_DeleteCollection_Call {
	return &mockBackupInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *mockBackupInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *mockBackupInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockBackupInterface_DeleteCollection_Call) Return(_a0 error) *mockBackupInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockBackupInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *mockBackupInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockBackupInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Backup, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.Backup, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.Backup); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockBackupInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockBackupInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockBackupInterface_Get_Call {
	return &mockBackupInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockBackupInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockBackupInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockBackupInterface_Get_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.Backup, error)) *mockBackupInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockBackupInterface) List(ctx context.Context, opts metav1.ListOptions) (*v1.BackupList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.BackupList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*v1.BackupList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *v1.BackupList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.BackupList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockBackupInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockBackupInterface_Expecter) List(ctx interface{}, opts interface{}) *mockBackupInterface_List_Call {
	return &mockBackupInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockBackupInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockBackupInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockBackupInterface_List_Call) Return(_a0 *v1.BackupList, _a1 error) *mockBackupInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*v1.BackupList, error)) *mockBackupInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *mockBackupInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*v1.Backup, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*v1.Backup, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *v1.Backup); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockBackupInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *mockBackupInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *mockBackupInterface_Patch_Call {
	return &mockBackupInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *mockBackupInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *mockBackupInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *mockBackupInterface_Patch_Call) Return(result *v1.Backup, err error) *mockBackupInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockBackupInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*v1.Backup, error)) *mockBackupInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFinalizer provides a mock function with given fields: ctx, _a1, finalizer
func (_m *mockBackupInterface) RemoveFinalizer(ctx context.Context, _a1 *v1.Backup, finalizer string) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFinalizer")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string) (*v1.Backup, error)); ok {
		return rf(ctx, _a1, finalizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, string) *v1.Backup); ok {
		r0 = rf(ctx, _a1, finalizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, string) error); ok {
		r1 = rf(ctx, _a1, finalizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_RemoveFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFinalizer'
type mockBackupInterface_RemoveFinalizer_Call struct {
	*mock.Call
}

// RemoveFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
//   - finalizer string
func (_e *mockBackupInterface_Expecter) RemoveFinalizer(ctx interface{}, _a1 interface{}, finalizer interface{}) *mockBackupInterface_RemoveFinalizer_Call {
	return &mockBackupInterface_RemoveFinalizer_Call{Call: _e.mock.On("RemoveFinalizer", ctx, _a1, finalizer)}
}

func (_c *mockBackupInterface_RemoveFinalizer_Call) Run(run func(ctx context.Context, _a1 *v1.Backup, finalizer string)) *mockBackupInterface_RemoveFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(string))
	})
	return _c
}

func (_c *mockBackupInterface_RemoveFinalizer_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_RemoveFinalizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_RemoveFinalizer_Call) RunAndReturn(run func(context.Context, *v1.Backup, string) (*v1.Backup, error)) *mockBackupInterface_RemoveFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, _a1, opts
func (_m *mockBackupInterface) Update(ctx context.Context, _a1 *v1.Backup, opts metav1.UpdateOptions) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, metav1.UpdateOptions) (*v1.Backup, error)); ok {
		return rf(ctx, _a1, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, metav1.UpdateOptions) *v1.Backup); ok {
		r0 = rf(ctx, _a1, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, _a1, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockBackupInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
//   - opts metav1.UpdateOptions
func (_e *mockBackupInterface_Expecter) Update(ctx interface{}, _a1 interface{}, opts interface{}) *mockBackupInterface_Update_Call {
	return &mockBackupInterface_Update_Call{Call: _e.mock.On("Update", ctx, _a1, opts)}
}

func (_c *mockBackupInterface_Update_Call) Run(run func(ctx context.Context, _a1 *v1.Backup, opts metav1.UpdateOptions)) *mockBackupInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockBackupInterface_Update_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_Update_Call) RunAndReturn(run func(context.Context, *v1.Backup, metav1.UpdateOptions) (*v1.Backup, error)) *mockBackupInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, _a1, opts
func (_m *mockBackupInterface) UpdateStatus(ctx context.Context, _a1 *v1.Backup, opts metav1.UpdateOptions) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, metav1.UpdateOptions) (*v1.Backup, error)); ok {
		return rf(ctx, _a1, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup, metav1.UpdateOptions) *v1.Backup); ok {
		r0 = rf(ctx, _a1, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, _a1, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type mockBackupInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
//   - opts metav1.UpdateOptions
func (_e *mockBackupInterface_Expecter) UpdateStatus(ctx interface{}, _a1 interface{}, opts interface{}) *mockBackupInterface_UpdateStatus_Call {
	return &mockBackupInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, _a1, opts)}
}

func (_c *mockBackupInterface_UpdateStatus_Call) Run(run func(ctx context.Context, _a1 *v1.Backup, opts metav1.UpdateOptions)) *mockBackupInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockBackupInterface_UpdateStatus_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *v1.Backup, metav1.UpdateOptions) (*v1.Backup, error)) *mockBackupInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusCompleted provides a mock function with given fields: ctx, _a1
func (_m *mockBackupInterface) UpdateStatusCompleted(ctx context.Context, _a1 *v1.Backup) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusCompleted")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_UpdateStatusCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusCompleted'
type mockBackupInterface_UpdateStatusCompleted_Call struct {
	*mock.Call
}

// UpdateStatusCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
func (_e *mockBackupInterface_Expecter) UpdateStatusCompleted(ctx interface{}, _a1 interface{}) *mockBackupInterface_UpdateStatusCompleted_Call {
	return &mockBackupInterface_UpdateStatusCompleted_Call{Call: _e.mock.On("UpdateStatusCompleted", ctx, _a1)}
}

func (_c *mockBackupInterface_UpdateStatusCompleted_Call) Run(run func(ctx context.Context, _a1 *v1.Backup)) *mockBackupInterface_UpdateStatusCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockBackupInterface_UpdateStatusCompleted_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_UpdateStatusCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_UpdateStatusCompleted_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, error)) *mockBackupInterface_UpdateStatusCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusDeleting provides a mock function with given fields: ctx, _a1
func (_m *mockBackupInterface) UpdateStatusDeleting(ctx context.Context, _a1 *v1.Backup) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusDeleting")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_UpdateStatusDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusDeleting'
type mockBackupInterface_UpdateStatusDeleting_Call struct {
	*mock.Call
}

// UpdateStatusDeleting is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
func (_e *mockBackupInterface_Expecter) UpdateStatusDeleting(ctx interface{}, _a1 interface{}) *mockBackupInterface_UpdateStatusDeleting_Call {
	return &mockBackupInterface_UpdateStatusDeleting_Call{Call: _e.mock.On("UpdateStatusDeleting", ctx, _a1)}
}

func (_c *mockBackupInterface_UpdateStatusDeleting_Call) Run(run func(ctx context.Context, _a1 *v1.Backup)) *mockBackupInterface_UpdateStatusDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockBackupInterface_UpdateStatusDeleting_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_UpdateStatusDeleting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_UpdateStatusDeleting_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, error)) *mockBackupInterface_UpdateStatusDeleting_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusFailed provides a mock function with given fields: ctx, _a1
func (_m *mockBackupInterface) UpdateStatusFailed(ctx context.Context, _a1 *v1.Backup) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusFailed")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_UpdateStatusFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusFailed'
type mockBackupInterface_UpdateStatusFailed_Call struct {
	*mock.Call
}

// UpdateStatusFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
func (_e *mockBackupInterface_Expecter) UpdateStatusFailed(ctx interface{}, _a1 interface{}) *mockBackupInterface_UpdateStatusFailed_Call {
	return &mockBackupInterface_UpdateStatusFailed_Call{Call: _e.mock.On("UpdateStatusFailed", ctx, _a1)}
}

func (_c *mockBackupInterface_UpdateStatusFailed_Call) Run(run func(ctx context.Context, _a1 *v1.Backup)) *mockBackupInterface_UpdateStatusFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockBackupInterface_UpdateStatusFailed_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_UpdateStatusFailed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_UpdateStatusFailed_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, error)) *mockBackupInterface_UpdateStatusFailed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusInProgress provides a mock function with given fields: ctx, _a1
func (_m *mockBackupInterface) UpdateStatusInProgress(ctx context.Context, _a1 *v1.Backup) (*v1.Backup, error) {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusInProgress")
	}

	var r0 *v1.Backup
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) (*v1.Backup, error)); ok {
		return rf(ctx, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Backup) *v1.Backup); ok {
		r0 = rf(ctx, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Backup)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Backup) error); ok {
		r1 = rf(ctx, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_UpdateStatusInProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusInProgress'
type mockBackupInterface_UpdateStatusInProgress_Call struct {
	*mock.Call
}

// UpdateStatusInProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *v1.Backup
func (_e *mockBackupInterface_Expecter) UpdateStatusInProgress(ctx interface{}, _a1 interface{}) *mockBackupInterface_UpdateStatusInProgress_Call {
	return &mockBackupInterface_UpdateStatusInProgress_Call{Call: _e.mock.On("UpdateStatusInProgress", ctx, _a1)}
}

func (_c *mockBackupInterface_UpdateStatusInProgress_Call) Run(run func(ctx context.Context, _a1 *v1.Backup)) *mockBackupInterface_UpdateStatusInProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Backup))
	})
	return _c
}

func (_c *mockBackupInterface_UpdateStatusInProgress_Call) Return(_a0 *v1.Backup, _a1 error) *mockBackupInterface_UpdateStatusInProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_UpdateStatusInProgress_Call) RunAndReturn(run func(context.Context, *v1.Backup) (*v1.Backup, error)) *mockBackupInterface_UpdateStatusInProgress_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockBackupInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBackupInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockBackupInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockBackupInterface_Expecter) Watch(ctx interface{}, opts interface{}) *mockBackupInterface_Watch_Call {
	return &mockBackupInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockBackupInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockBackupInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockBackupInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockBackupInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBackupInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *mockBackupInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBackupInterface creates a new instance of mockBackupInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBackupInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBackupInterface {
	mock := &mockBackupInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
