// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	types "k8s.io/apimachinery/pkg/types"

	v1 "github.com/cloudogu/k8s-backup-lib/api/v1"

	watch "k8s.io/apimachinery/pkg/watch"
)

// mockRestoreInterface is an autogenerated mock type for the restoreInterface type
type mockRestoreInterface struct {
	mock.Mock
}

type mockRestoreInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *mockRestoreInterface) EXPECT() *mockRestoreInterface_Expecter {
	return &mockRestoreInterface_Expecter{mock: &_m.Mock}
}

// AddFinalizer provides a mock function with given fields: ctx, restore, finalizer
func (_m *mockRestoreInterface) AddFinalizer(ctx context.Context, restore *v1.Restore, finalizer string) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for AddFinalizer")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, string) (*v1.Restore, error)); ok {
		return rf(ctx, restore, finalizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, string) *v1.Restore); ok {
		r0 = rf(ctx, restore, finalizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore, string) error); ok {
		r1 = rf(ctx, restore, finalizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_AddFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddFinalizer'
type mockRestoreInterface_AddFinalizer_Call struct {
	*mock.Call
}

// AddFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
//   - finalizer string
func (_e *mockRestoreInterface_Expecter) AddFinalizer(ctx interface{}, restore interface{}, finalizer interface{}) *mockRestoreInterface_AddFinalizer_Call {
	return &mockRestoreInterface_AddFinalizer_Call{Call: _e.mock.On("AddFinalizer", ctx, restore, finalizer)}
}

func (_c *mockRestoreInterface_AddFinalizer_Call) Run(run func(ctx context.Context, restore *v1.Restore, finalizer string)) *mockRestoreInterface_AddFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore), args[2].(string))
	})
	return _c
}

func (_c *mockRestoreInterface_AddFinalizer_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_AddFinalizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_AddFinalizer_Call) RunAndReturn(run func(context.Context, *v1.Restore, string) (*v1.Restore, error)) *mockRestoreInterface_AddFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// AddLabels provides a mock function with given fields: ctx, restore
func (_m *mockRestoreInterface) AddLabels(ctx context.Context, restore *v1.Restore) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore)

	if len(ret) == 0 {
		panic("no return value specified for AddLabels")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) (*v1.Restore, error)); ok {
		return rf(ctx, restore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) *v1.Restore); ok {
		r0 = rf(ctx, restore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore) error); ok {
		r1 = rf(ctx, restore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_AddLabels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddLabels'
type mockRestoreInterface_AddLabels_Call struct {
	*mock.Call
}

// AddLabels is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
func (_e *mockRestoreInterface_Expecter) AddLabels(ctx interface{}, restore interface{}) *mockRestoreInterface_AddLabels_Call {
	return &mockRestoreInterface_AddLabels_Call{Call: _e.mock.On("AddLabels", ctx, restore)}
}

func (_c *mockRestoreInterface_AddLabels_Call) Run(run func(ctx context.Context, restore *v1.Restore)) *mockRestoreInterface_AddLabels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore))
	})
	return _c
}

func (_c *mockRestoreInterface_AddLabels_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_AddLabels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_AddLabels_Call) RunAndReturn(run func(context.Context, *v1.Restore) (*v1.Restore, error)) *mockRestoreInterface_AddLabels_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, restore, opts
func (_m *mockRestoreInterface) Create(ctx context.Context, restore *v1.Restore, opts metav1.CreateOptions) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore, opts)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, metav1.CreateOptions) (*v1.Restore, error)); ok {
		return rf(ctx, restore, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, metav1.CreateOptions) *v1.Restore); ok {
		r0 = rf(ctx, restore, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore, metav1.CreateOptions) error); ok {
		r1 = rf(ctx, restore, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockRestoreInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
//   - opts metav1.CreateOptions
func (_e *mockRestoreInterface_Expecter) Create(ctx interface{}, restore interface{}, opts interface{}) *mockRestoreInterface_Create_Call {
	return &mockRestoreInterface_Create_Call{Call: _e.mock.On("Create", ctx, restore, opts)}
}

func (_c *mockRestoreInterface_Create_Call) Run(run func(ctx context.Context, restore *v1.Restore, opts metav1.CreateOptions)) *mockRestoreInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore), args[2].(metav1.CreateOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_Create_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_Create_Call) RunAndReturn(run func(context.Context, *v1.Restore, metav1.CreateOptions) (*v1.Restore, error)) *mockRestoreInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, name, opts
func (_m *mockRestoreInterface) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.DeleteOptions) error); ok {
		r0 = rf(ctx, name, opts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRestoreInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mockRestoreInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.DeleteOptions
func (_e *mockRestoreInterface_Expecter) Delete(ctx interface{}, name interface{}, opts interface{}) *mockRestoreInterface_Delete_Call {
	return &mockRestoreInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, name, opts)}
}

func (_c *mockRestoreInterface_Delete_Call) Run(run func(ctx context.Context, name string, opts metav1.DeleteOptions)) *mockRestoreInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.DeleteOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_Delete_Call) Return(_a0 error) *mockRestoreInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRestoreInterface_Delete_Call) RunAndReturn(run func(context.Context, string, metav1.DeleteOptions) error) *mockRestoreInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function with given fields: ctx, opts, listOpts
func (_m *mockRestoreInterface) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	ret := _m.Called(ctx, opts, listOpts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error); ok {
		r0 = rf(ctx, opts, listOpts)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockRestoreInterface_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type mockRestoreInterface_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.DeleteOptions
//   - listOpts metav1.ListOptions
func (_e *mockRestoreInterface_Expecter) DeleteCollection(ctx interface{}, opts interface{}, listOpts interface{}) *mockRestoreInterface_DeleteCollection_Call {
	return &mockRestoreInterface_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection", ctx, opts, listOpts)}
}

func (_c *mockRestoreInterface_DeleteCollection_Call) Run(run func(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions)) *mockRestoreInterface_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.DeleteOptions), args[2].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_DeleteCollection_Call) Return(_a0 error) *mockRestoreInterface_DeleteCollection_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockRestoreInterface_DeleteCollection_Call) RunAndReturn(run func(context.Context, metav1.DeleteOptions, metav1.ListOptions) error) *mockRestoreInterface_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, name, opts
func (_m *mockRestoreInterface) Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.Restore, error) {
	ret := _m.Called(ctx, name, opts)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) (*v1.Restore, error)); ok {
		return rf(ctx, name, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, metav1.GetOptions) *v1.Restore); ok {
		r0 = rf(ctx, name, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, metav1.GetOptions) error); ok {
		r1 = rf(ctx, name, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockRestoreInterface_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - opts metav1.GetOptions
func (_e *mockRestoreInterface_Expecter) Get(ctx interface{}, name interface{}, opts interface{}) *mockRestoreInterface_Get_Call {
	return &mockRestoreInterface_Get_Call{Call: _e.mock.On("Get", ctx, name, opts)}
}

func (_c *mockRestoreInterface_Get_Call) Run(run func(ctx context.Context, name string, opts metav1.GetOptions)) *mockRestoreInterface_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(metav1.GetOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_Get_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_Get_Call) RunAndReturn(run func(context.Context, string, metav1.GetOptions) (*v1.Restore, error)) *mockRestoreInterface_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockRestoreInterface) List(ctx context.Context, opts metav1.ListOptions) (*v1.RestoreList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v1.RestoreList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (*v1.RestoreList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) *v1.RestoreList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.RestoreList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockRestoreInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockRestoreInterface_Expecter) List(ctx interface{}, opts interface{}) *mockRestoreInterface_List_Call {
	return &mockRestoreInterface_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockRestoreInterface_List_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockRestoreInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_List_Call) Return(_a0 *v1.RestoreList, _a1 error) *mockRestoreInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_List_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (*v1.RestoreList, error)) *mockRestoreInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Patch provides a mock function with given fields: ctx, name, pt, data, opts, subresources
func (_m *mockRestoreInterface) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (*v1.Restore, error) {
	_va := make([]interface{}, len(subresources))
	for _i := range subresources {
		_va[_i] = subresources[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, name, pt, data, opts)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Patch")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*v1.Restore, error)); ok {
		return rf(ctx, name, pt, data, opts, subresources...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) *v1.Restore); ok {
		r0 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) error); ok {
		r1 = rf(ctx, name, pt, data, opts, subresources...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_Patch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Patch'
type mockRestoreInterface_Patch_Call struct {
	*mock.Call
}

// Patch is a helper method to define mock.On call
//   - ctx context.Context
//   - name string
//   - pt types.PatchType
//   - data []byte
//   - opts metav1.PatchOptions
//   - subresources ...string
func (_e *mockRestoreInterface_Expecter) Patch(ctx interface{}, name interface{}, pt interface{}, data interface{}, opts interface{}, subresources ...interface{}) *mockRestoreInterface_Patch_Call {
	return &mockRestoreInterface_Patch_Call{Call: _e.mock.On("Patch",
		append([]interface{}{ctx, name, pt, data, opts}, subresources...)...)}
}

func (_c *mockRestoreInterface_Patch_Call) Run(run func(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string)) *mockRestoreInterface_Patch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-5)
		for i, a := range args[5:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(context.Context), args[1].(string), args[2].(types.PatchType), args[3].([]byte), args[4].(metav1.PatchOptions), variadicArgs...)
	})
	return _c
}

func (_c *mockRestoreInterface_Patch_Call) Return(result *v1.Restore, err error) *mockRestoreInterface_Patch_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *mockRestoreInterface_Patch_Call) RunAndReturn(run func(context.Context, string, types.PatchType, []byte, metav1.PatchOptions, ...string) (*v1.Restore, error)) *mockRestoreInterface_Patch_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveFinalizer provides a mock function with given fields: ctx, restore, finalizer
func (_m *mockRestoreInterface) RemoveFinalizer(ctx context.Context, restore *v1.Restore, finalizer string) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore, finalizer)

	if len(ret) == 0 {
		panic("no return value specified for RemoveFinalizer")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, string) (*v1.Restore, error)); ok {
		return rf(ctx, restore, finalizer)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, string) *v1.Restore); ok {
		r0 = rf(ctx, restore, finalizer)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore, string) error); ok {
		r1 = rf(ctx, restore, finalizer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_RemoveFinalizer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveFinalizer'
type mockRestoreInterface_RemoveFinalizer_Call struct {
	*mock.Call
}

// RemoveFinalizer is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
//   - finalizer string
func (_e *mockRestoreInterface_Expecter) RemoveFinalizer(ctx interface{}, restore interface{}, finalizer interface{}) *mockRestoreInterface_RemoveFinalizer_Call {
	return &mockRestoreInterface_RemoveFinalizer_Call{Call: _e.mock.On("RemoveFinalizer", ctx, restore, finalizer)}
}

func (_c *mockRestoreInterface_RemoveFinalizer_Call) Run(run func(ctx context.Context, restore *v1.Restore, finalizer string)) *mockRestoreInterface_RemoveFinalizer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore), args[2].(string))
	})
	return _c
}

func (_c *mockRestoreInterface_RemoveFinalizer_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_RemoveFinalizer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_RemoveFinalizer_Call) RunAndReturn(run func(context.Context, *v1.Restore, string) (*v1.Restore, error)) *mockRestoreInterface_RemoveFinalizer_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, restore, opts
func (_m *mockRestoreInterface) Update(ctx context.Context, restore *v1.Restore, opts metav1.UpdateOptions) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore, opts)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, metav1.UpdateOptions) (*v1.Restore, error)); ok {
		return rf(ctx, restore, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, metav1.UpdateOptions) *v1.Restore); ok {
		r0 = rf(ctx, restore, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, restore, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockRestoreInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
//   - opts metav1.UpdateOptions
func (_e *mockRestoreInterface_Expecter) Update(ctx interface{}, restore interface{}, opts interface{}) *mockRestoreInterface_Update_Call {
	return &mockRestoreInterface_Update_Call{Call: _e.mock.On("Update", ctx, restore, opts)}
}

func (_c *mockRestoreInterface_Update_Call) Run(run func(ctx context.Context, restore *v1.Restore, opts metav1.UpdateOptions)) *mockRestoreInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_Update_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_Update_Call) RunAndReturn(run func(context.Context, *v1.Restore, metav1.UpdateOptions) (*v1.Restore, error)) *mockRestoreInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatus provides a mock function with given fields: ctx, restore, opts
func (_m *mockRestoreInterface) UpdateStatus(ctx context.Context, restore *v1.Restore, opts metav1.UpdateOptions) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore, opts)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatus")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, metav1.UpdateOptions) (*v1.Restore, error)); ok {
		return rf(ctx, restore, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore, metav1.UpdateOptions) *v1.Restore); ok {
		r0 = rf(ctx, restore, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore, metav1.UpdateOptions) error); ok {
		r1 = rf(ctx, restore, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_UpdateStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatus'
type mockRestoreInterface_UpdateStatus_Call struct {
	*mock.Call
}

// UpdateStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
//   - opts metav1.UpdateOptions
func (_e *mockRestoreInterface_Expecter) UpdateStatus(ctx interface{}, restore interface{}, opts interface{}) *mockRestoreInterface_UpdateStatus_Call {
	return &mockRestoreInterface_UpdateStatus_Call{Call: _e.mock.On("UpdateStatus", ctx, restore, opts)}
}

func (_c *mockRestoreInterface_UpdateStatus_Call) Run(run func(ctx context.Context, restore *v1.Restore, opts metav1.UpdateOptions)) *mockRestoreInterface_UpdateStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore), args[2].(metav1.UpdateOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_UpdateStatus_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_UpdateStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_UpdateStatus_Call) RunAndReturn(run func(context.Context, *v1.Restore, metav1.UpdateOptions) (*v1.Restore, error)) *mockRestoreInterface_UpdateStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusCompleted provides a mock function with given fields: ctx, restore
func (_m *mockRestoreInterface) UpdateStatusCompleted(ctx context.Context, restore *v1.Restore) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusCompleted")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) (*v1.Restore, error)); ok {
		return rf(ctx, restore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) *v1.Restore); ok {
		r0 = rf(ctx, restore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore) error); ok {
		r1 = rf(ctx, restore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_UpdateStatusCompleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusCompleted'
type mockRestoreInterface_UpdateStatusCompleted_Call struct {
	*mock.Call
}

// UpdateStatusCompleted is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
func (_e *mockRestoreInterface_Expecter) UpdateStatusCompleted(ctx interface{}, restore interface{}) *mockRestoreInterface_UpdateStatusCompleted_Call {
	return &mockRestoreInterface_UpdateStatusCompleted_Call{Call: _e.mock.On("UpdateStatusCompleted", ctx, restore)}
}

func (_c *mockRestoreInterface_UpdateStatusCompleted_Call) Run(run func(ctx context.Context, restore *v1.Restore)) *mockRestoreInterface_UpdateStatusCompleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore))
	})
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusCompleted_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_UpdateStatusCompleted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusCompleted_Call) RunAndReturn(run func(context.Context, *v1.Restore) (*v1.Restore, error)) *mockRestoreInterface_UpdateStatusCompleted_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusDeleting provides a mock function with given fields: ctx, restore
func (_m *mockRestoreInterface) UpdateStatusDeleting(ctx context.Context, restore *v1.Restore) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusDeleting")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) (*v1.Restore, error)); ok {
		return rf(ctx, restore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) *v1.Restore); ok {
		r0 = rf(ctx, restore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore) error); ok {
		r1 = rf(ctx, restore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_UpdateStatusDeleting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusDeleting'
type mockRestoreInterface_UpdateStatusDeleting_Call struct {
	*mock.Call
}

// UpdateStatusDeleting is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
func (_e *mockRestoreInterface_Expecter) UpdateStatusDeleting(ctx interface{}, restore interface{}) *mockRestoreInterface_UpdateStatusDeleting_Call {
	return &mockRestoreInterface_UpdateStatusDeleting_Call{Call: _e.mock.On("UpdateStatusDeleting", ctx, restore)}
}

func (_c *mockRestoreInterface_UpdateStatusDeleting_Call) Run(run func(ctx context.Context, restore *v1.Restore)) *mockRestoreInterface_UpdateStatusDeleting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore))
	})
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusDeleting_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_UpdateStatusDeleting_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusDeleting_Call) RunAndReturn(run func(context.Context, *v1.Restore) (*v1.Restore, error)) *mockRestoreInterface_UpdateStatusDeleting_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusFailed provides a mock function with given fields: ctx, restore
func (_m *mockRestoreInterface) UpdateStatusFailed(ctx context.Context, restore *v1.Restore) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusFailed")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) (*v1.Restore, error)); ok {
		return rf(ctx, restore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) *v1.Restore); ok {
		r0 = rf(ctx, restore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore) error); ok {
		r1 = rf(ctx, restore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_UpdateStatusFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusFailed'
type mockRestoreInterface_UpdateStatusFailed_Call struct {
	*mock.Call
}

// UpdateStatusFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
func (_e *mockRestoreInterface_Expecter) UpdateStatusFailed(ctx interface{}, restore interface{}) *mockRestoreInterface_UpdateStatusFailed_Call {
	return &mockRestoreInterface_UpdateStatusFailed_Call{Call: _e.mock.On("UpdateStatusFailed", ctx, restore)}
}

func (_c *mockRestoreInterface_UpdateStatusFailed_Call) Run(run func(ctx context.Context, restore *v1.Restore)) *mockRestoreInterface_UpdateStatusFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore))
	})
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusFailed_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_UpdateStatusFailed_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusFailed_Call) RunAndReturn(run func(context.Context, *v1.Restore) (*v1.Restore, error)) *mockRestoreInterface_UpdateStatusFailed_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStatusInProgress provides a mock function with given fields: ctx, restore
func (_m *mockRestoreInterface) UpdateStatusInProgress(ctx context.Context, restore *v1.Restore) (*v1.Restore, error) {
	ret := _m.Called(ctx, restore)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusInProgress")
	}

	var r0 *v1.Restore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) (*v1.Restore, error)); ok {
		return rf(ctx, restore)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.Restore) *v1.Restore); ok {
		r0 = rf(ctx, restore)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Restore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.Restore) error); ok {
		r1 = rf(ctx, restore)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_UpdateStatusInProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStatusInProgress'
type mockRestoreInterface_UpdateStatusInProgress_Call struct {
	*mock.Call
}

// UpdateStatusInProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - restore *v1.Restore
func (_e *mockRestoreInterface_Expecter) UpdateStatusInProgress(ctx interface{}, restore interface{}) *mockRestoreInterface_UpdateStatusInProgress_Call {
	return &mockRestoreInterface_UpdateStatusInProgress_Call{Call: _e.mock.On("UpdateStatusInProgress", ctx, restore)}
}

func (_c *mockRestoreInterface_UpdateStatusInProgress_Call) Run(run func(ctx context.Context, restore *v1.Restore)) *mockRestoreInterface_UpdateStatusInProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*v1.Restore))
	})
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusInProgress_Call) Return(_a0 *v1.Restore, _a1 error) *mockRestoreInterface_UpdateStatusInProgress_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_UpdateStatusInProgress_Call) RunAndReturn(run func(context.Context, *v1.Restore) (*v1.Restore, error)) *mockRestoreInterface_UpdateStatusInProgress_Call {
	_c.Call.Return(run)
	return _c
}

// Watch provides a mock function with given fields: ctx, opts
func (_m *mockRestoreInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for Watch")
	}

	var r0 watch.Interface
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) (watch.Interface, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, metav1.ListOptions) watch.Interface); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(watch.Interface)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, metav1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockRestoreInterface_Watch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Watch'
type mockRestoreInterface_Watch_Call struct {
	*mock.Call
}

// Watch is a helper method to define mock.On call
//   - ctx context.Context
//   - opts metav1.ListOptions
func (_e *mockRestoreInterface_Expecter) Watch(ctx interface{}, opts interface{}) *mockRestoreInterface_Watch_Call {
	return &mockRestoreInterface_Watch_Call{Call: _e.mock.On("Watch", ctx, opts)}
}

func (_c *mockRestoreInterface_Watch_Call) Run(run func(ctx context.Context, opts metav1.ListOptions)) *mockRestoreInterface_Watch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(metav1.ListOptions))
	})
	return _c
}

func (_c *mockRestoreInterface_Watch_Call) Return(_a0 watch.Interface, _a1 error) *mockRestoreInterface_Watch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockRestoreInterface_Watch_Call) RunAndReturn(run func(context.Context, metav1.ListOptions) (watch.Interface, error)) *mockRestoreInterface_Watch_Call {
	_c.Call.Return(run)
	return _c
}

// newMockRestoreInterface creates a new instance of mockRestoreInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockRestoreInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockRestoreInterface {
	mock := &mockRestoreInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
