// Code generated by mockery v2.53.3. DO NOT EDIT.

package backup

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v3 "github.com/cloudogu/k8s-blueprint-lib/v3/api/v3"
)

// mockBlueprintLister is an autogenerated mock type for the blueprintLister type
type mockBlueprintLister struct {
	mock.Mock
}

type mockBlueprintLister_Expecter struct {
	mock *mock.Mock
}

func (_m *mockBlueprintLister) EXPECT() *mockBlueprintLister_Expecter {
	return &mockBlueprintLister_Expecter{mock: &_m.Mock}
}

// List provides a mock function with given fields: ctx, opts
func (_m *mockBlueprintLister) List(ctx context.Context, opts v1.ListOptions) (*v3.BlueprintList, error) {
	ret := _m.Called(ctx, opts)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *v3.BlueprintList
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) (*v3.BlueprintList, error)); ok {
		return rf(ctx, opts)
	}
	if rf, ok := ret.Get(0).(func(context.Context, v1.ListOptions) *v3.BlueprintList); ok {
		r0 = rf(ctx, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v3.BlueprintList)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, v1.ListOptions) error); ok {
		r1 = rf(ctx, opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockBlueprintLister_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type mockBlueprintLister_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - opts v1.ListOptions
func (_e *mockBlueprintLister_Expecter) List(ctx interface{}, opts interface{}) *mockBlueprintLister_List_Call {
	return &mockBlueprintLister_List_Call{Call: _e.mock.On("List", ctx, opts)}
}

func (_c *mockBlueprintLister_List_Call) Run(run func(ctx context.Context, opts v1.ListOptions)) *mockBlueprintLister_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(v1.ListOptions))
	})
	return _c
}

func (_c *mockBlueprintLister_List_Call) Return(_a0 *v3.BlueprintList, _a1 error) *mockBlueprintLister_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockBlueprintLister_List_Call) RunAndReturn(run func(context.Context, v1.ListOptions) (*v3.BlueprintList, error)) *mockBlueprintLister_List_Call {
	_c.Call.Return(run)
	return _c
}

// newMockBlueprintLister creates a new instance of mockBlueprintLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockBlueprintLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockBlueprintLister {
	mock := &mockBlueprintLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
