global:
  networkPolicies:
    enabled: true
    denyIngress: true
  imagePullSecrets:
    - name: "ces-container-registries"
manager:
  image:
    registry: docker.io
    repository: cloudogu/k8s-ces-control
    tag: 1.6.0
  imagePullPolicy: IfNotPresent
  replicas: 1
  env:
    stage: production
    logLevel: info
  resourceLimits:
    memory: 105M
  resourceRequests:
    cpu: 50m
    memory: 105M
lokiGateway:
  url: "http://k8s-loki-gateway.ecosystem.svc.cluster.local"
  secretName: "k8s-loki-gateway-secret"
  usernameKey: "username"
  passwordKey: "password"
