// Code generated by mockery v2.20.0. DO NOT EDIT.

package account

import (
	keys "github.com/cloudogu/cesapp-lib/keys"
	mock "github.com/stretchr/testify/mock"
)

// mockKeyProvider is an autogenerated mock type for the keyProvider type
type mockKeyProvider struct {
	mock.Mock
}

type mockKeyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockKeyProvider) EXPECT() *mockKeyProvider_Expecter {
	return &mockKeyProvider_Expecter{mock: &_m.Mock}
}

// FromPrivateKey provides a mock function with given fields: privateKey
func (_m *mockKeyProvider) FromPrivateKey(privateKey []byte) (*keys.KeyPair, error) {
	ret := _m.Called(privateKey)

	var r0 *keys.KeyPair
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (*keys.KeyPair, error)); ok {
		return rf(privateKey)
	}
	if rf, ok := ret.Get(0).(func([]byte) *keys.KeyPair); ok {
		r0 = rf(privateKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.KeyPair)
		}
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(privateKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockKeyProvider_FromPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromPrivateKey'
type mockKeyProvider_FromPrivateKey_Call struct {
	*mock.Call
}

// FromPrivateKey is a helper method to define mock.On call
//   - privateKey []byte
func (_e *mockKeyProvider_Expecter) FromPrivateKey(privateKey []byte) *mockKeyProvider_FromPrivateKey_Call {
	return &mockKeyProvider_FromPrivateKey_Call{Call: _e.mock.On("FromPrivateKey", privateKey)}
}

func (_c *mockKeyProvider_FromPrivateKey_Call) Run(run func(privateKey []byte)) *mockKeyProvider_FromPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *mockKeyProvider_FromPrivateKey_Call) Return(_a0 *keys.KeyPair, _a1 error) *mockKeyProvider_FromPrivateKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockKeyProvider_FromPrivateKey_Call) RunAndReturn(run func([]byte) (*keys.KeyPair, error)) *mockKeyProvider_FromPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockKeyProvider interface {
	mock.TestingT
	Cleanup(func())
}

// newMockKeyProvider creates a new instance of mockKeyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockKeyProvider(t mockConstructorTestingTnewMockKeyProvider) *mockKeyProvider {
	mock := &mockKeyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
