// Code generated by mockery v2.20.0. DO NOT EDIT.

package account

import (
	keys "github.com/cloudogu/cesapp-lib/keys"
	mock "github.com/stretchr/testify/mock"
)

// mockKeyProvider is an autogenerated mock type for the keyProvider type
type mockKeyProvider struct {
	mock.Mock
}

type mockKeyProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *mockKeyProvider) EXPECT() *mockKeyProvider_Expecter {
	return &mockKeyProvider_Expecter{mock: &_m.Mock}
}

// FromPrivateKeyPath provides a mock function with given fields: path
func (_m *mockKeyProvider) FromPrivateKeyPath(path string) (*keys.KeyPair, error) {
	ret := _m.Called(path)

	var r0 *keys.KeyPair
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*keys.KeyPair, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) *keys.KeyPair); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*keys.KeyPair)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockKeyProvider_FromPrivateKeyPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FromPrivateKeyPath'
type mockKeyProvider_FromPrivateKeyPath_Call struct {
	*mock.Call
}

// FromPrivateKeyPath is a helper method to define mock.On call
//   - path string
func (_e *mockKeyProvider_Expecter) FromPrivateKeyPath(path interface{}) *mockKeyProvider_FromPrivateKeyPath_Call {
	return &mockKeyProvider_FromPrivateKeyPath_Call{Call: _e.mock.On("FromPrivateKeyPath", path)}
}

func (_c *mockKeyProvider_FromPrivateKeyPath_Call) Run(run func(path string)) *mockKeyProvider_FromPrivateKeyPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *mockKeyProvider_FromPrivateKeyPath_Call) Return(_a0 *keys.KeyPair, _a1 error) *mockKeyProvider_FromPrivateKeyPath_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockKeyProvider_FromPrivateKeyPath_Call) RunAndReturn(run func(string) (*keys.KeyPair, error)) *mockKeyProvider_FromPrivateKeyPath_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockKeyProvider interface {
	mock.TestingT
	Cleanup(func())
}

// newMockKeyProvider creates a new instance of mockKeyProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockKeyProvider(t mockConstructorTestingTnewMockKeyProvider) *mockKeyProvider {
	mock := &mockKeyProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
