// Code generated by mockery v2.53.3. DO NOT EDIT.

package doguAdministration

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguDescriptorGetter is an autogenerated mock type for the doguDescriptorGetter type
type mockDoguDescriptorGetter struct {
	mock.Mock
}

type mockDoguDescriptorGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguDescriptorGetter) EXPECT() *mockDoguDescriptorGetter_Expecter {
	return &mockDoguDescriptorGetter_Expecter{mock: &_m.Mock}
}

// GetCurrentOfAll provides a mock function with given fields: ctx
func (_m *mockDoguDescriptorGetter) GetCurrentOfAll(ctx context.Context) ([]*core.Dogu, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrentOfAll")
	}

	var r0 []*core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*core.Dogu, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*core.Dogu); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguDescriptorGetter_GetCurrentOfAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrentOfAll'
type mockDoguDescriptorGetter_GetCurrentOfAll_Call struct {
	*mock.Call
}

// GetCurrentOfAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockDoguDescriptorGetter_Expecter) GetCurrentOfAll(ctx interface{}) *mockDoguDescriptorGetter_GetCurrentOfAll_Call {
	return &mockDoguDescriptorGetter_GetCurrentOfAll_Call{Call: _e.mock.On("GetCurrentOfAll", ctx)}
}

func (_c *mockDoguDescriptorGetter_GetCurrentOfAll_Call) Run(run func(ctx context.Context)) *mockDoguDescriptorGetter_GetCurrentOfAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockDoguDescriptorGetter_GetCurrentOfAll_Call) Return(_a0 []*core.Dogu, _a1 error) *mockDoguDescriptorGetter_GetCurrentOfAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguDescriptorGetter_GetCurrentOfAll_Call) RunAndReturn(run func(context.Context) ([]*core.Dogu, error)) *mockDoguDescriptorGetter_GetCurrentOfAll_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguDescriptorGetter creates a new instance of mockDoguDescriptorGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguDescriptorGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguDescriptorGetter {
	mock := &mockDoguDescriptorGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
