// Code generated by mockery v2.53.5. DO NOT EDIT.

package doguAdministration

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguInterActor is an autogenerated mock type for the doguInterActor type
type mockDoguInterActor struct {
	mock.Mock
}

type mockDoguInterActor_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguInterActor) EXPECT() *mockDoguInterActor_Expecter {
	return &mockDoguInterActor_Expecter{mock: &_m.Mock}
}

// RestartDogu provides a mock function with given fields: ctx, doguName
func (_m *mockDoguInterActor) RestartDogu(ctx context.Context, doguName string) error {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for RestartDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguInterActor_RestartDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartDogu'
type mockDoguInterActor_RestartDogu_Call struct {
	*mock.Call
}

// RestartDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *mockDoguInterActor_Expecter) RestartDogu(ctx interface{}, doguName interface{}) *mockDoguInterActor_RestartDogu_Call {
	return &mockDoguInterActor_RestartDogu_Call{Call: _e.mock.On("RestartDogu", ctx, doguName)}
}

func (_c *mockDoguInterActor_RestartDogu_Call) Run(run func(ctx context.Context, doguName string)) *mockDoguInterActor_RestartDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDoguInterActor_RestartDogu_Call) Return(_a0 error) *mockDoguInterActor_RestartDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguInterActor_RestartDogu_Call) RunAndReturn(run func(context.Context, string) error) *mockDoguInterActor_RestartDogu_Call {
	_c.Call.Return(run)
	return _c
}

// StartDogu provides a mock function with given fields: ctx, doguName
func (_m *mockDoguInterActor) StartDogu(ctx context.Context, doguName string) error {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for StartDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguInterActor_StartDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartDogu'
type mockDoguInterActor_StartDogu_Call struct {
	*mock.Call
}

// StartDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *mockDoguInterActor_Expecter) StartDogu(ctx interface{}, doguName interface{}) *mockDoguInterActor_StartDogu_Call {
	return &mockDoguInterActor_StartDogu_Call{Call: _e.mock.On("StartDogu", ctx, doguName)}
}

func (_c *mockDoguInterActor_StartDogu_Call) Run(run func(ctx context.Context, doguName string)) *mockDoguInterActor_StartDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDoguInterActor_StartDogu_Call) Return(_a0 error) *mockDoguInterActor_StartDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguInterActor_StartDogu_Call) RunAndReturn(run func(context.Context, string) error) *mockDoguInterActor_StartDogu_Call {
	_c.Call.Return(run)
	return _c
}

// StopDogu provides a mock function with given fields: ctx, doguName
func (_m *mockDoguInterActor) StopDogu(ctx context.Context, doguName string) error {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for StopDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguInterActor_StopDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StopDogu'
type mockDoguInterActor_StopDogu_Call struct {
	*mock.Call
}

// StopDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *mockDoguInterActor_Expecter) StopDogu(ctx interface{}, doguName interface{}) *mockDoguInterActor_StopDogu_Call {
	return &mockDoguInterActor_StopDogu_Call{Call: _e.mock.On("StopDogu", ctx, doguName)}
}

func (_c *mockDoguInterActor_StopDogu_Call) Run(run func(ctx context.Context, doguName string)) *mockDoguInterActor_StopDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDoguInterActor_StopDogu_Call) Return(_a0 error) *mockDoguInterActor_StopDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguInterActor_StopDogu_Call) RunAndReturn(run func(context.Context, string) error) *mockDoguInterActor_StopDogu_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguInterActor creates a new instance of mockDoguInterActor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguInterActor(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguInterActor {
	mock := &mockDoguInterActor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
