// Code generated by mockery v2.42.1. DO NOT EDIT.

package logging

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// mockDoguRestarter is an autogenerated mock type for the doguRestarter type
type mockDoguRestarter struct {
	mock.Mock
}

type mockDoguRestarter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguRestarter) EXPECT() *mockDoguRestarter_Expecter {
	return &mockDoguRestarter_Expecter{mock: &_m.Mock}
}

// RestartDogu provides a mock function with given fields: ctx, doguName
func (_m *mockDoguRestarter) RestartDogu(ctx context.Context, doguName string) error {
	ret := _m.Called(ctx, doguName)

	if len(ret) == 0 {
		panic("no return value specified for RestartDogu")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, doguName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguRestarter_RestartDogu_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartDogu'
type mockDoguRestarter_RestartDogu_Call struct {
	*mock.Call
}

// RestartDogu is a helper method to define mock.On call
//   - ctx context.Context
//   - doguName string
func (_e *mockDoguRestarter_Expecter) RestartDogu(ctx interface{}, doguName interface{}) *mockDoguRestarter_RestartDogu_Call {
	return &mockDoguRestarter_RestartDogu_Call{Call: _e.mock.On("RestartDogu", ctx, doguName)}
}

func (_c *mockDoguRestarter_RestartDogu_Call) Run(run func(ctx context.Context, doguName string)) *mockDoguRestarter_RestartDogu_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDoguRestarter_RestartDogu_Call) Return(_a0 error) *mockDoguRestarter_RestartDogu_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguRestarter_RestartDogu_Call) RunAndReturn(run func(context.Context, string) error) *mockDoguRestarter_RestartDogu_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguRestarter creates a new instance of mockDoguRestarter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguRestarter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguRestarter {
	mock := &mockDoguRestarter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
