// Code generated by mockery v2.53.5. DO NOT EDIT.

package logging

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguDescriptorGetter is an autogenerated mock type for the doguDescriptorGetter type
type mockDoguDescriptorGetter struct {
	mock.Mock
}

type mockDoguDescriptorGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguDescriptorGetter) EXPECT() *mockDoguDescriptorGetter_Expecter {
	return &mockDoguDescriptorGetter_Expecter{mock: &_m.Mock}
}

// GetCurrent provides a mock function with given fields: ctx, simpleDoguName
func (_m *mockDoguDescriptorGetter) GetCurrent(ctx context.Context, simpleDoguName string) (*core.Dogu, error) {
	ret := _m.Called(ctx, simpleDoguName)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrent")
	}

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.Dogu, error)); ok {
		return rf(ctx, simpleDoguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.Dogu); ok {
		r0 = rf(ctx, simpleDoguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, simpleDoguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguDescriptorGetter_GetCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrent'
type mockDoguDescriptorGetter_GetCurrent_Call struct {
	*mock.Call
}

// GetCurrent is a helper method to define mock.On call
//   - ctx context.Context
//   - simpleDoguName string
func (_e *mockDoguDescriptorGetter_Expecter) GetCurrent(ctx interface{}, simpleDoguName interface{}) *mockDoguDescriptorGetter_GetCurrent_Call {
	return &mockDoguDescriptorGetter_GetCurrent_Call{Call: _e.mock.On("GetCurrent", ctx, simpleDoguName)}
}

func (_c *mockDoguDescriptorGetter_GetCurrent_Call) Run(run func(ctx context.Context, simpleDoguName string)) *mockDoguDescriptorGetter_GetCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDoguDescriptorGetter_GetCurrent_Call) Return(_a0 *core.Dogu, _a1 error) *mockDoguDescriptorGetter_GetCurrent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguDescriptorGetter_GetCurrent_Call) RunAndReturn(run func(context.Context, string) (*core.Dogu, error)) *mockDoguDescriptorGetter_GetCurrent_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguDescriptorGetter creates a new instance of mockDoguDescriptorGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguDescriptorGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguDescriptorGetter {
	mock := &mockDoguDescriptorGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
