// Code generated by mockery v2.20.0. DO NOT EDIT.

package logging

import (
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// mockNowClock is an autogenerated mock type for the nowClock type
type mockNowClock struct {
	mock.Mock
}

type mockNowClock_Expecter struct {
	mock *mock.Mock
}

func (_m *mockNowClock) EXPECT() *mockNowClock_Expecter {
	return &mockNowClock_Expecter{mock: &_m.Mock}
}

// Now provides a mock function with given fields:
func (_m *mockNowClock) Now() time.Time {
	ret := _m.Called()

	var r0 time.Time
	if rf, ok := ret.Get(0).(func() time.Time); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	return r0
}

// mockNowClock_Now_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Now'
type mockNowClock_Now_Call struct {
	*mock.Call
}

// Now is a helper method to define mock.On call
func (_e *mockNowClock_Expecter) Now() *mockNowClock_Now_Call {
	return &mockNowClock_Now_Call{Call: _e.mock.On("Now")}
}

func (_c *mockNowClock_Now_Call) Run(run func()) *mockNowClock_Now_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockNowClock_Now_Call) Return(_a0 time.Time) *mockNowClock_Now_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockNowClock_Now_Call) RunAndReturn(run func() time.Time) *mockNowClock_Now_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockNowClock interface {
	mock.TestingT
	Cleanup(func())
}

// newMockNowClock creates a new instance of mockNowClock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockNowClock(t mockConstructorTestingTnewMockNowClock) *mockNowClock {
	mock := &mockNowClock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
