// Code generated by mockery v2.20.0. DO NOT EDIT.

package logging

import (
	context "context"

	core "github.com/cloudogu/cesapp-lib/core"
	mock "github.com/stretchr/testify/mock"
)

// mockDoguDescriptionGetter is an autogenerated mock type for the doguDescriptionGetter type
type mockDoguDescriptionGetter struct {
	mock.Mock
}

type mockDoguDescriptionGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguDescriptionGetter) EXPECT() *mockDoguDescriptionGetter_Expecter {
	return &mockDoguDescriptionGetter_Expecter{mock: &_m.Mock}
}

// GetCurrent provides a mock function with given fields: ctx, simpleDoguName
func (_m *mockDoguDescriptionGetter) GetCurrent(ctx context.Context, simpleDoguName string) (*core.Dogu, error) {
	ret := _m.Called(ctx, simpleDoguName)

	var r0 *core.Dogu
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*core.Dogu, error)); ok {
		return rf(ctx, simpleDoguName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *core.Dogu); ok {
		r0 = rf(ctx, simpleDoguName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Dogu)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, simpleDoguName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDoguDescriptionGetter_GetCurrent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCurrent'
type mockDoguDescriptionGetter_GetCurrent_Call struct {
	*mock.Call
}

// GetCurrent is a helper method to define mock.On call
//   - ctx context.Context
//   - simpleDoguName string
func (_e *mockDoguDescriptionGetter_Expecter) GetCurrent(ctx interface{}, simpleDoguName interface{}) *mockDoguDescriptionGetter_GetCurrent_Call {
	return &mockDoguDescriptionGetter_GetCurrent_Call{Call: _e.mock.On("GetCurrent", ctx, simpleDoguName)}
}

func (_c *mockDoguDescriptionGetter_GetCurrent_Call) Run(run func(ctx context.Context, simpleDoguName string)) *mockDoguDescriptionGetter_GetCurrent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockDoguDescriptionGetter_GetCurrent_Call) Return(_a0 *core.Dogu, _a1 error) *mockDoguDescriptionGetter_GetCurrent_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDoguDescriptionGetter_GetCurrent_Call) RunAndReturn(run func(context.Context, string) (*core.Dogu, error)) *mockDoguDescriptionGetter_GetCurrent_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTnewMockDoguDescriptionGetter interface {
	mock.TestingT
	Cleanup(func())
}

// newMockDoguDescriptionGetter creates a new instance of mockDoguDescriptionGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func newMockDoguDescriptionGetter(t mockConstructorTestingTnewMockDoguDescriptionGetter) *mockDoguDescriptionGetter {
	mock := &mockDoguDescriptionGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
