// Code generated by mockery v2.42.1. DO NOT EDIT.

package logging

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	types "github.com/cloudogu/ces-control-api/generated/types"
)

// mockDoguLogMessagesServer is an autogenerated mock type for the doguLogMessagesServer type
type mockDoguLogMessagesServer struct {
	mock.Mock
}

type mockDoguLogMessagesServer_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDoguLogMessagesServer) EXPECT() *mockDoguLogMessagesServer_Expecter {
	return &mockDoguLogMessagesServer_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *mockDoguLogMessagesServer) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// mockDoguLogMessagesServer_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type mockDoguLogMessagesServer_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *mockDoguLogMessagesServer_Expecter) Context() *mockDoguLogMessagesServer_Context_Call {
	return &mockDoguLogMessagesServer_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *mockDoguLogMessagesServer_Context_Call) Run(run func()) *mockDoguLogMessagesServer_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockDoguLogMessagesServer_Context_Call) Return(_a0 context.Context) *mockDoguLogMessagesServer_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguLogMessagesServer_Context_Call) RunAndReturn(run func() context.Context) *mockDoguLogMessagesServer_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *mockDoguLogMessagesServer) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguLogMessagesServer_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type mockDoguLogMessagesServer_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *mockDoguLogMessagesServer_Expecter) RecvMsg(m interface{}) *mockDoguLogMessagesServer_RecvMsg_Call {
	return &mockDoguLogMessagesServer_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *mockDoguLogMessagesServer_RecvMsg_Call) Run(run func(m interface{})) *mockDoguLogMessagesServer_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *mockDoguLogMessagesServer_RecvMsg_Call) Return(_a0 error) *mockDoguLogMessagesServer_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguLogMessagesServer_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *mockDoguLogMessagesServer_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *mockDoguLogMessagesServer) Send(_a0 *types.ChunkedDataResponse) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*types.ChunkedDataResponse) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguLogMessagesServer_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type mockDoguLogMessagesServer_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *types.ChunkedDataResponse
func (_e *mockDoguLogMessagesServer_Expecter) Send(_a0 interface{}) *mockDoguLogMessagesServer_Send_Call {
	return &mockDoguLogMessagesServer_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *mockDoguLogMessagesServer_Send_Call) Run(run func(_a0 *types.ChunkedDataResponse)) *mockDoguLogMessagesServer_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*types.ChunkedDataResponse))
	})
	return _c
}

func (_c *mockDoguLogMessagesServer_Send_Call) Return(_a0 error) *mockDoguLogMessagesServer_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguLogMessagesServer_Send_Call) RunAndReturn(run func(*types.ChunkedDataResponse) error) *mockDoguLogMessagesServer_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *mockDoguLogMessagesServer) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguLogMessagesServer_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type mockDoguLogMessagesServer_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *mockDoguLogMessagesServer_Expecter) SendHeader(_a0 interface{}) *mockDoguLogMessagesServer_SendHeader_Call {
	return &mockDoguLogMessagesServer_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *mockDoguLogMessagesServer_SendHeader_Call) Run(run func(_a0 metadata.MD)) *mockDoguLogMessagesServer_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *mockDoguLogMessagesServer_SendHeader_Call) Return(_a0 error) *mockDoguLogMessagesServer_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguLogMessagesServer_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *mockDoguLogMessagesServer_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *mockDoguLogMessagesServer) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguLogMessagesServer_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type mockDoguLogMessagesServer_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *mockDoguLogMessagesServer_Expecter) SendMsg(m interface{}) *mockDoguLogMessagesServer_SendMsg_Call {
	return &mockDoguLogMessagesServer_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *mockDoguLogMessagesServer_SendMsg_Call) Run(run func(m interface{})) *mockDoguLogMessagesServer_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *mockDoguLogMessagesServer_SendMsg_Call) Return(_a0 error) *mockDoguLogMessagesServer_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguLogMessagesServer_SendMsg_Call) RunAndReturn(run func(interface{}) error) *mockDoguLogMessagesServer_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *mockDoguLogMessagesServer) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockDoguLogMessagesServer_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type mockDoguLogMessagesServer_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *mockDoguLogMessagesServer_Expecter) SetHeader(_a0 interface{}) *mockDoguLogMessagesServer_SetHeader_Call {
	return &mockDoguLogMessagesServer_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *mockDoguLogMessagesServer_SetHeader_Call) Run(run func(_a0 metadata.MD)) *mockDoguLogMessagesServer_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *mockDoguLogMessagesServer_SetHeader_Call) Return(_a0 error) *mockDoguLogMessagesServer_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockDoguLogMessagesServer_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *mockDoguLogMessagesServer_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *mockDoguLogMessagesServer) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// mockDoguLogMessagesServer_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type mockDoguLogMessagesServer_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *mockDoguLogMessagesServer_Expecter) SetTrailer(_a0 interface{}) *mockDoguLogMessagesServer_SetTrailer_Call {
	return &mockDoguLogMessagesServer_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *mockDoguLogMessagesServer_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *mockDoguLogMessagesServer_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *mockDoguLogMessagesServer_SetTrailer_Call) Return() *mockDoguLogMessagesServer_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *mockDoguLogMessagesServer_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *mockDoguLogMessagesServer_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDoguLogMessagesServer creates a new instance of mockDoguLogMessagesServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDoguLogMessagesServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDoguLogMessagesServer {
	mock := &mockDoguLogMessagesServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
