apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-ces-control.name" . }}
  labels:
    {{- include "k8s-ces-control.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "k8s-ces-control.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-ces-control.name" . }}
    namespace: '{{ .Release.Namespace }}'