# This handles all permissions necessary to enable/disable debug mode in admin dogu
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-ces-control.name" . }}-dogu-debug-mode-role
  labels:
    {{- include "k8s-ces-control.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - update
      - create
      - get
      - list
      - delete
  # allow dogu deployments to be listed/inspected and to be scaled for stopping/starting/restarting during debug mode
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
    verbs:
      - watch
      - update
      - list
      - get
