# This handles all permissions necessary to list dogus on main page of admin dogu
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-ces-control.name" . }}-dogu-list-role
  labels:
    {{- include "k8s-ces-control.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
  # allow dogu deployments to be listed/inspected and to be scaled for stopping/starting/restarting
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - get