apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-ces-control.name" . }}
  labels:
    {{- include "k8s-ces-control.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: 50051
      targetPort: grpc-port
  selector:
    app.kubernetes.io/name: k8s-ces-control