# This handles all permissions necessary to create the support archive
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "k8s-ces-control.name" . }}-support-archive-role
  labels:
    {{- include "k8s-ces-control.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - list
      - get
